name: build-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn build:wasm

      - uses: actions/upload-artifact@v2
        with:
          name: awk-parser-wasm
          path: tree-sitter-awk.wasm
